<?php
/**
 * Implements hook_menu().
 */
function taxonomy_updater_menu() {
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/update-terms'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Update terms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('update_terms_form', 3),
    'access arguments' => array('access taxonomy updater'),
    'file' => 'includes/taxonomy_updater_page.admin.inc'
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function taxonomy_updater_permission() {
  return array(
    'access taxonomy updater' =>  array(
      'title' => t('Access taxonomy updater process'),
      'description' => t('Let user to perform taxonomy updating process.'),
    ),
  );
}